# Generated by Django 6.0.3 on 2026-03-18 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qanda", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="solution",
            options={"ordering": ["-is_accepted", "-created_at"]},
        ),
    ]
